Repository AdaSupport/zendesk-web-sdk, pull requests merged in 2019-10, with the labels that each got.

#7 INT-958: Add Fallback Preservation of Conversation
  web-sdk.js
Labels: size/M

#8 Update SDK to allow setting the debug function
  web-sdk.js
Labels: size/XS

#9 Update SDK to send over stringified error event
  web-sdk.js
Labels: size/XS

#10 Update SDK to send over stringified error even Pt. 2
  web-sdk.js
Labels: size/XS

#13 Change the way the overrides work
  web-sdk.js
Labels: size/S
